name: label
on: pull_request
jobs:
  label-prs:
    runs-on: ubuntu-latest
    steps:
    - name: Label PRs - main HEAD
      uses: actions/labeler@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: ".github/labeler.yml"
    - name: Label PRs
      uses: actions/labeler@v3-preview
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: ".github/labeler.yml"
    - name: Test pagination
      uses: actions/labeler@releases/v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: ".github/many-files.yml"
    - name: Test pagination on main
      uses: actions/labeler@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: ".github/many-files.yml"
