name: label
on: pull_request
jobs:
  label-prs:
    runs-on: ubuntu-latest
    steps:
    - name: Label PRs
      uses: actions/labeler@v3-preview
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
